### PR TITLE
Update Gems 

### PR DESCRIPTION
**Pull request by paulsa**
Updating Gems

### CODE REVIEW

**Comment by SamuelGarratt** [comment]
@paulsa I got all tests working except 
"Managing customers Adding a new customer"
"Managing customers Adding a new customer whose order has already been delivered"

**Comment by SamuelGarratt** [comment]
It's working now @paulsa  and @ducktyper .
However there is a deprecation warning
```
.DEPRECATION WARNING: You have passed an ActionController::Parameters to Authlogic 3. That's
OK for now, but in Authlogic 4, it will raise an error. Please
replace:
    UserSession.new(user_session_params)
    UserSession.create(user_session_params)
with
    UserSession.new(user_session_params.to_h)
    UserSession.create(user_session_params.to_h)
And don't forget to `permit`!
```

**Comment by ducktyper** [comment]
@SamuelGarratt I copied your fixes required to pass Travis CI into a new pull request https://github.com/BFNZ/bfnz/pull/42

About the deprecation warning, adding `.to_h` will be good enough. The `permit` method is already being used to the `user_session_params`.

```
  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
```
The `permit` method limits which request parameters to use to avoid unexpected parameters being used.

**Comment by SamuelGarratt** [comment]
Thank you @ducktyper

**Pull request closed without merging**
