### PR TITLE
Rr table

### PR DESCRIPTION
**Pull request by ReganRyanNZ**
fixed the normal order bug

### CODE REVIEW

**Comment by ypcamp** [comment]
Normal order not returning any error now

**Comment by SamuelGarratt** [comment]
Normal order is working as expected now

**Comment by SamuelGarratt** [comment]
However table is not working. It's now complaining about a person needing to confirm their personal order which (from the table page is not possible) @ReganRyanNZ

**Comment by SamuelGarratt** [comment]
Below is response I got
image
The key value pair confirm_personal_order is not being set to 1 as it is in normal order form. The query being made is:
Parameters: {"utf8"=>"✓", "authenticity_token"=>"7J92NQpMY/NtBi6bg+Spmu5TkELl11c1htHSeA99p24=", "table_id"=>"1", "customer_and_order_form"=>{"tertiary_student"=>"1", "tertiary_institution"=>"Victoria", "title"=>"Miss", "first_name"=>"Chessie", "last_name"=>"Bon Bee", "address"=>"45 Not in here place", "suburb"=>"", "city_town"=>"", "post_code"=>"", "pxid"=>"", "dpid"=>"", "x"=>"", "y"=>"", "ta"=>"", "phone"=>"", "email"=>"", "further_contact_requested"=>"0"}, "commit"=>"Submit"}

Compare that with parameters from an order from the normal link
Parameters: {"utf8"=>"✓", "authenticity_token"=>"7J92NQpMY/NtBi6bg+Spmu5TkELl11c1htHSeA99p24=", "customer_and_order_form"=>{**"confirm_personal_order"=>"1"**, "title"=>"Mrs", "first_name"=>"Fsdjl", "last_name"=>"lkJGDfs", "address"=>"63 A Renall Road, Pollok 2684", "suburb"=>"", "city_town"=>"", "post_code"=>"", "pxid"=>"", "dpid"=>"", "x"=>"", "y"=>"", "ta"=>"", "phone"=>"", "email"=>"", "tertiary_student"=>"0", "tertiary_institution"=>"", "item_ids"=>["", "1"], "further_contact_requested"=>"0"}, "commit"=>"Place Order"}

**Comment by SamuelGarratt** [comment]
@ReganRyanNZ @paulsa I made a tiny change that fixed the problem. Changed setting personal order by default (on table) from true to 1. Now both order forms work.

**Pull request merged**
